#pragma once

#include <algorithm>
#include <memory>
#include <set>
#include <string>
#include <vector>

namespace InterSubMod {

/**
 * @brief Tree node structure
 *
 * Used to represent binary trees generated by hierarchical clustering. Each node may be:
 * - Leaf node: represents a read, has label but no children
 * - Internal node: represents a cluster merge, has left and right children
 */
struct TreeNode {
    int node_id = -1;                ///< Node ID (leaf nodes 0..N-1, internal nodes N..2N-2)
    std::string label;               ///< Node label (for leaf nodes, read_id or name)
    double height = 0.0;             ///< Node height (distance from leaf nodes)
    double branch_length = 0.0;      ///< Branch length to parent
    double bootstrap_support = 0.0;  ///< Bootstrap support (0-100)

    std::shared_ptr<TreeNode> left;   ///< Left subtree
    std::shared_ptr<TreeNode> right;  ///< Right subtree
    std::weak_ptr<TreeNode> parent;   ///< Parent node (weak_ptr to avoid circular reference)

    std::vector<int> leaf_indices;  ///< Leaf node indices in this clade (sorted)

    /**
     * @brief Check if this is a leaf node
     */
    bool is_leaf() const {
        return left == nullptr && right == nullptr;
    }

    /**
     * @brief Get number of leaf nodes under this node
     */
    int num_leaves() const {
        return static_cast<int>(leaf_indices.size());
    }

    /**
     * @brief Create leaf node
     */
    static std::shared_ptr<TreeNode> create_leaf(int index, const std::string& name) {
        auto node = std::make_shared<TreeNode>();
        node->node_id = index;
        node->label = name;
        node->height = 0.0;
        node->branch_length = 0.0;
        node->bootstrap_support = 100.0;  // Leaf node default support 100
        node->leaf_indices = {index};
        return node;
    }

    /**
     * @brief Create internal node
     */
    static std::shared_ptr<TreeNode> create_internal(int node_id, std::shared_ptr<TreeNode> left_child,
                                                     std::shared_ptr<TreeNode> right_child, double merge_height) {
        auto node = std::make_shared<TreeNode>();
        node->node_id = node_id;
        node->label = "";  // Internal node has no label
        node->height = merge_height;
        node->bootstrap_support = 0.0;  // Initial 0, filled in by Bootstrap later

        node->left = left_child;
        node->right = right_child;

        // Calculate branch lengths
        if (left_child) {
            left_child->branch_length = merge_height - left_child->height;
            left_child->parent = node;
        }
        if (right_child) {
            right_child->branch_length = merge_height - right_child->height;
            right_child->parent = node;
        }

        // Merge leaf_indices
        node->leaf_indices = left_child ? left_child->leaf_indices : std::vector<int>{};
        if (right_child) {
            node->leaf_indices.insert(node->leaf_indices.end(), right_child->leaf_indices.begin(),
                                      right_child->leaf_indices.end());
        }
        std::sort(node->leaf_indices.begin(), node->leaf_indices.end());

        return node;
    }
};

/**
 * @brief Cluster merge record
 *
 * Records detailed information for each merge, similar to scipy's linkage matrix format
 */
struct MergeRecord {
    int cluster_i;       ///< First cluster ID being merged
    int cluster_j;       ///< Second cluster ID being merged
    double distance;     ///< Distance at merge
    int new_cluster_id;  ///< New cluster ID after merge
    int size;            ///< Number of leaf nodes in new cluster
};

/**
 * @brief Phylogenetic tree structure
 *
 * Encapsulates complete tree structure, providing:
 * - Newick format output
 * - Internal node traversal
 * - Bootstrap support annotation
 * - Clade comparison functionality
 */
class Tree {
public:
    Tree() = default;

    /**
     * @brief Set tree root
     */
    void set_root(std::shared_ptr<TreeNode> root) {
        root_ = root;
    }

    /**
     * @brief Get tree root
     */
    std::shared_ptr<TreeNode> get_root() const {
        return root_;
    }

    /**
     * @brief Check if tree is empty
     */
    bool empty() const {
        return root_ == nullptr;
    }

    /**
     * @brief Get number of leaf nodes
     */
    int num_leaves() const {
        return root_ ? root_->num_leaves() : 0;
    }

    /**
     * @brief Get number of internal nodes
     */
    int num_internal_nodes() const {
        return root_ ? static_cast<int>(get_internal_nodes().size()) : 0;
    }

    /**
     * @brief Convert to Newick format string
     *
     * @param include_bootstrap Whether to include Bootstrap support
     * @param include_branch_length Whether to include branch lengths
     * @param precision Floating-point precision
     * @return Newick format string
     */
    std::string to_newick(bool include_bootstrap = true, bool include_branch_length = true, int precision = 6) const;

    /**
     * @brief Get all internal nodes (for Bootstrap analysis)
     *
     * Returns all internal nodes in pre-order
     */
    std::vector<std::shared_ptr<TreeNode>> get_internal_nodes() const;

    /**
     * @brief Get all leaf nodes
     *
     * Returns all leaf nodes in in-order
     */
    std::vector<std::shared_ptr<TreeNode>> get_leaves() const;

    /**
     * @brief Annotate Bootstrap support values
     *
     * @param support_values Support value for each internal node (corresponding to get_internal_nodes() order)
     */
    void annotate_bootstrap_support(const std::vector<double>& support_values);

    /**
     * @brief Get leaf_indices sets for all clades
     *
     * Used for Bootstrap comparison
     */
    std::vector<std::set<int>> get_all_clades() const;

    /**
     * @brief Set merge records (for debugging and validation)
     */
    void set_merge_records(const std::vector<MergeRecord>& records) {
        merge_records_ = records;
    }

    /**
     * @brief Get merge records
     */
    const std::vector<MergeRecord>& get_merge_records() const {
        return merge_records_;
    }

    /**
     * @brief Deep copy entire tree
     */
    Tree deep_copy() const;

private:
    std::shared_ptr<TreeNode> root_;
    std::vector<MergeRecord> merge_records_;

    /**
     * @brief Recursively generate Newick string
     */
    std::string newick_recursive(const std::shared_ptr<TreeNode>& node, bool include_bootstrap,
                                 bool include_branch_length, int precision) const;

    /**
     * @brief Recursively collect internal nodes
     */
    void collect_internal_nodes(const std::shared_ptr<TreeNode>& node,
                                std::vector<std::shared_ptr<TreeNode>>& nodes,
                                std::set<const TreeNode*>& visited) const;

    /**
     * @brief Recursively collect leaf nodes
     */
    void collect_leaves(const std::shared_ptr<TreeNode>& node, std::vector<std::shared_ptr<TreeNode>>& leaves,
                        std::set<const TreeNode*>& visited) const;

    /**
     * @brief Recursively collect all clades
     */
    void collect_clades(const std::shared_ptr<TreeNode>& node, std::vector<std::set<int>>& clades) const;

    /**
     * @brief Recursively deep copy node
     */
    std::shared_ptr<TreeNode> deep_copy_node(const std::shared_ptr<TreeNode>& node) const;
};

}  // namespace InterSubMod
