#!/usr/bin/env python3
"""Independent tests for the current-funnel verifier.

The fixture is assembled directly in this test and never imports the producer
receipt builder, preserving implementation independence.
"""

from __future__ import annotations

import importlib.util
import json
import sys
import tempfile
import unittest
from pathlib import Path


HERE = Path(__file__).resolve().parent
SCRIPT = HERE.parent / "scripts" / "verify_current_funnel_receipt.py"
SPEC = importlib.util.spec_from_file_location("verify_current_funnel", SCRIPT)
VERIFY = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
sys.modules[SPEC.name] = VERIFY
SPEC.loader.exec_module(VERIFY)


# Values are copied from the frozen source-ledger contract, not generated by the
# receipt builder.  Each tuple is raw, filter-excluded, non-autosomal,
# MAX_SNV-excluded, singleton, retained.
SOURCE_COUNTS = {
    "COLO829": (43014, 3556, 1670, 2202, 7830, 27756),
    "H1437": (83261, 3606, 2575, 32841, 6696, 37543),
    "H2009": (168638, 7043, 7130, 100448, 2853, 51164),
    "HCC1395": (134122, 21061, 33374, 44306, 8279, 27102),
    "HCC1395_DORADO": (123240, 10095, 33406, 43803, 8321, 27615),
    "HCC1937": (59161, 7046, 33425, 890, 8469, 9331),
    "HCC1954": (26823, 3032, 1391, 778, 7984, 13638),
}


def ratio(numerator: int, denominator: int) -> float | None:
    return numerator / denominator if denominator else None


class CurrentFunnelIndependentVerifierTest(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name)
        self.ledger_root = self.root / "canonical"
        self.canonical_path = self.root / "canonical.json"
        self.receipt_path = self.root / "receipt.json"

        canonical_rows = []
        receipt_rows = []
        source_rows = []
        aggregate = {
            "raw_clairs_records": 0,
            "longphase_s_recalibrated_pass": 0,
            "autosomal_biallelic_sSNV": 0,
            "retained_sSNV": 0,
        }
        aggregate_branches = {name: 0 for name in VERIFY.EXPECTED_BRANCHES}

        for dataset in VERIFY.EXPECTED_DATASETS:
            raw, excluded, non_autosomal, max_excluded, singleton, retained = SOURCE_COUNTS[dataset]
            tree = raw - excluded
            autosomal = tree - non_autosomal
            branches = {
                "excluded_by_longphase_filter": excluded,
                "out_of_scope_non_autosomal": non_autosomal,
                "max_snv_excluded": max_excluded,
                "positional_singleton": singleton,
                "retained": retained,
            }
            self.assertEqual(autosomal, max_excluded + singleton + retained)
            ledger = {
                "schema_version": "2.0",
                "sample": dataset,
                "pass": True,
                "longphase_input_contract": "clairs_raw_all",
                "tree_contract": "longphase_recalibrated_PASS",
                "raw_clairs_records": raw,
                "longphase_input_records": raw,
                "longphase_recalibrated_records": raw,
                "tree_input_records": tree,
                "autosomal_biallelic_snvs": autosomal,
                "branch_counts": branches,
                "checks": {name: True for name in VERIFY.LEDGER_CHECKS},
                "duplicate_record_key_excess": {
                    "raw_clairs": 0,
                    "longphase_input": 0,
                    "longphase_recalibrated": 0,
                    "tree_input": 0,
                },
            }
            ledger_path = self.ledger_root / "samples" / dataset / f"ssnv_site_ledger_{dataset}.summary.json"
            ledger_path.parent.mkdir(parents=True)
            ledger_path.write_text(json.dumps(ledger, sort_keys=True) + "\n", encoding="utf-8")
            ledger_hash = VERIFY.file_sha256(ledger_path)

            canonical_rows.append(
                {
                    "sample": dataset,
                    "tree_input_records": tree,
                    "autosomal_biallelic_sSNV": autosomal,
                    "retained_sSNV": retained,
                }
            )
            receipt_rows.append(
                {
                    "dataset": dataset,
                    "raw_clairs_records": raw,
                    "longphase_s_recalibrated_pass": tree,
                    "autosomal_biallelic_sSNV": autosomal,
                    "retained_sSNV": retained,
                    "relative_ratios": {
                        "longphase_pass_over_raw": ratio(tree, raw),
                        "autosomal_over_longphase_pass": ratio(autosomal, tree),
                        "retained_over_autosomal": ratio(retained, autosomal),
                    },
                    "total_ratios_over_raw": {
                        "autosomal": ratio(autosomal, raw),
                        "retained": ratio(retained, raw),
                    },
                    "branch_counts": branches,
                    "source_path": str(ledger_path.resolve()),
                    "source_sha256": ledger_hash,
                }
            )
            source_rows.append({"dataset": dataset, "path": str(ledger_path.resolve()), "sha256": ledger_hash})
            aggregate["raw_clairs_records"] += raw
            aggregate["longphase_s_recalibrated_pass"] += tree
            aggregate["autosomal_biallelic_sSNV"] += autosomal
            aggregate["retained_sSNV"] += retained
            for name, value in branches.items():
                aggregate_branches[name] += value

        canonical = {
            "all_pass": True,
            "canonical": {
                "aggregate": {
                    "dataset_count": 7,
                    "tree_input_records": aggregate["longphase_s_recalibrated_pass"],
                    "autosomal_biallelic_sSNV": aggregate["autosomal_biallelic_sSNV"],
                    "retained_sSNV": aggregate["retained_sSNV"],
                },
                "samples": canonical_rows,
            },
        }
        self.canonical_path.write_text(json.dumps(canonical, sort_keys=True) + "\n", encoding="utf-8")

        raw = aggregate["raw_clairs_records"]
        tree = aggregate["longphase_s_recalibrated_pass"]
        autosomal = aggregate["autosomal_biallelic_sSNV"]
        retained = aggregate["retained_sSNV"]
        receipt = {
            "schema_name": "intersubmod_current_ssnv_funnel_receipt",
            "schema_version": "1.0.0",
            "generated_at": "2026-07-16T00:00:00+08:00",
            "task_type": "B_comprehensive_validation",
            "scope": {
                "datasets": list(VERIFY.EXPECTED_DATASETS),
                "dataset_count": 7,
                "biological_sample_count": 6,
                "chromosomes": "chr1-chr22 for autosomal_biallelic_sSNV and downstream",
                "technical_replication_note": "test",
            },
            "inputs": {
                "canonical_json": {
                    "path": str(self.canonical_path.resolve()),
                    "sha256": VERIFY.file_sha256(self.canonical_path),
                },
                "site_ledger_root": str(self.ledger_root.resolve()),
                "site_ledger_summaries": source_rows,
            },
            "aggregate": {
                **aggregate,
                "branch_counts": aggregate_branches,
                "relative_ratios": {
                    "longphase_pass_over_raw": ratio(tree, raw),
                    "autosomal_over_longphase_pass": ratio(autosomal, tree),
                    "retained_over_autosomal": ratio(retained, autosomal),
                },
                "total_ratios_over_raw": {
                    "autosomal": ratio(autosomal, raw),
                    "retained": ratio(retained, raw),
                },
            },
            "datasets": receipt_rows,
            "checks": {name: True for name in VERIFY.RECEIPT_CHECKS},
            "all_pass": True,
        }
        self.receipt_path.write_text(json.dumps(receipt, sort_keys=True) + "\n", encoding="utf-8")

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def verify(self) -> dict:
        return VERIFY.verify_funnel(self.canonical_path, self.ledger_root, self.receipt_path)

    def test_independently_recomputes_all_headline_counts(self) -> None:
        result = self.verify()
        self.assertTrue(result["all_pass"], result["failures"])
        self.assertEqual(result["n_fail"], 0)
        recomputed = result["recomputed"]["aggregate"]
        self.assertEqual(recomputed["raw_clairs_records"], 638259)
        self.assertEqual(recomputed["longphase_s_recalibrated_pass"], 582820)
        self.assertEqual(recomputed["autosomal_biallelic_sSNV"], 469849)
        self.assertEqual(recomputed["branch_counts"]["positional_singleton"], 50432)
        self.assertEqual(recomputed["branch_counts"]["max_snv_excluded"], 225268)
        self.assertEqual(recomputed["retained_sSNV"], 194149)
        self.assertEqual(recomputed["autosomal_partition_identity"], "50432 + 225268 + 194149 = 469849")

    def test_rejects_tampered_receipt_aggregate(self) -> None:
        receipt = json.loads(self.receipt_path.read_text(encoding="utf-8"))
        receipt["aggregate"]["retained_sSNV"] += 1
        self.receipt_path.write_text(json.dumps(receipt, sort_keys=True) + "\n", encoding="utf-8")
        result = self.verify()
        self.assertFalse(result["all_pass"])
        self.assertTrue(any("receipt aggregate retained_sSNV 不符" in failure for failure in result["failures"]))

    def test_rejects_source_conservation_break_and_hash_drift(self) -> None:
        dataset = "COLO829"
        ledger_path = self.ledger_root / "samples" / dataset / f"ssnv_site_ledger_{dataset}.summary.json"
        ledger = json.loads(ledger_path.read_text(encoding="utf-8"))
        ledger["branch_counts"]["positional_singleton"] += 1
        ledger_path.write_text(json.dumps(ledger, sort_keys=True) + "\n", encoding="utf-8")
        result = self.verify()
        self.assertFalse(result["all_pass"])
        self.assertTrue(any("五個互斥 branch 不等於 raw" in failure for failure in result["failures"]))
        self.assertTrue(any("receipt input source SHA-256 不符" in failure for failure in result["failures"]))

    def test_rejects_dataset_order_and_duplicate(self) -> None:
        receipt = json.loads(self.receipt_path.read_text(encoding="utf-8"))
        receipt["datasets"][1] = receipt["datasets"][0]
        self.receipt_path.write_text(json.dumps(receipt, sort_keys=True) + "\n", encoding="utf-8")
        result = self.verify()
        self.assertFalse(result["all_pass"])
        self.assertFalse(result["checks"]["receipt_dataset_order"])
        self.assertFalse(result["checks"]["receipt_dataset_unique"])

    def test_rejects_ratio_drift(self) -> None:
        receipt = json.loads(self.receipt_path.read_text(encoding="utf-8"))
        receipt["datasets"][0]["relative_ratios"]["retained_over_autosomal"] = 0.5
        self.receipt_path.write_text(json.dumps(receipt, sort_keys=True) + "\n", encoding="utf-8")
        result = self.verify()
        self.assertFalse(result["all_pass"])
        self.assertTrue(
            any(
                "receipt ratio relative_ratios.retained_over_autosomal 不符" in failure
                for failure in result["failures"]
            )
        )


if __name__ == "__main__":
    unittest.main()
