#!/usr/bin/env python3
"""V5 Audit Suite — Sanity (Layer 1.5 conservation) + Paired ground-truth concordance.

Generated by Agent D for the V5 Audit Suite (`docs/reports/pi_reports/2026/04/v5_audit_suite/`).

Three analyses run on the same 15 sites used by the rest of the audit suite:

  A. V5 Sanity Check (conservation laws + Layer 1.5 expectations)
       Law A: V3F → V5 only redistributes HP33 to HP11 / HP21
              ΔHP33 must equal -(ΔHP11 + ΔHP21).
       Law B: Germline (HP1, HP2) tag counts unchanged V3F → V5.
       Layer 1.5 expectation 1: every read whose tag changes V3F=33 → V5∈{11,21}
              must equal ΔHP11 / ΔHP21 exactly (no other source for new directional tags).
       Layer 1.5 expectation 2: zero reads with V3F∈{1,2} → V5=33
              (germline must never be demoted to ambiguous by Layer 1.5).

  B. Paired ground-truth per-read concordance
       For every read present in BL ∩ V5 ∩ Paired, compare V5_HP and BL_HP to
       Paired_HP (HP:Z string from the paired BAM). PS-block orientation flip
       is handled by picking the orientation (identity or 1<->2 swap) that
       maximises germline (HP1/HP2 reads in V3F) concordance per site.

  C. Cross-site aggregate / verdict + 4 figures + 2 TSVs.

Outputs
-------
  data/sanity_check.tsv              per-site sanity verification
  data/paired_ground_truth.tsv       per-site paired concordance
  figures/06_sanity/fig06a_conservation_verification.png
  figures/06_sanity/fig06b_layer15_expectation.png
  figures/07_paired/fig07a_paired_concordance_per_site.png
  figures/07_paired/fig07b_clean_vs_problem_ps.png
"""
from __future__ import annotations

import csv
import os
from collections import Counter, defaultdict
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pysam

# Force CJK fallback so titles/labels render on shared infra (per project rule).
plt.rcParams["font.family"] = ["DejaVu Sans", "Droid Sans Fallback", "Noto Sans CJK TC"]
plt.rcParams["axes.unicode_minus"] = False

# ---------------------------------------------------------------------------
# Inputs (locked by Agent A and the rest of the V5 audit suite).
# ---------------------------------------------------------------------------
BL_BAM = "/big7_disk/liaoyoyo2001/longphase-to-mod/output/baseline/tumor_tagged.bam"
V3F_BAM = "/big7_disk/liaoyoyo2001/longphase-to-mod/output/pononly_v3_fixed/tumor_tagged.bam"
V5_BAM = "/big7_disk/liaoyoyo2001/longphase-to-mod/output/pononly_v5_somatic_fallback/tumor_tagged.bam"
PAIRED_BAM = "/big8_disk/liaoyoyo2001/InterSubMod/data/bam/HCC1395/tumor.bam"

SUITE_ROOT = Path("/big7_disk/liaoyoyo2001/InterSubMod/docs/reports/pi_reports/2026/04/v5_audit_suite")
DATA_DIR = SUITE_ROOT / "data"
FIG_SANITY_DIR = SUITE_ROOT / "figures" / "06_sanity"
FIG_PAIRED_DIR = SUITE_ROOT / "figures" / "07_paired"
for d in (DATA_DIR, FIG_SANITY_DIR, FIG_PAIRED_DIR):
    d.mkdir(parents=True, exist_ok=True)

# 15 sites used across the audit suite (5 TP, 4 FP, 3 V5-reassign hotspots, 3 SP-extreme).
SITES: list[tuple[str, str, int, str, str]] = [
    ("A_TP01", "chr6", 145444893, "TP", "Phase4 TP"),
    ("A_TP02", "chr4", 70548355, "TP", "Phase4 TP"),
    ("A_TP03", "chr5", 153209947, "TP", "Phase4 TP"),
    ("A_TP04", "chr16", 35118902, "TP", "Phase4 TP"),
    ("A_TP05", "chr7", 109185781, "TP", "Phase4 TP"),
    ("B_FPA1", "chr8", 93565727, "FP", "Phase4 FP A"),
    ("B_FPA2", "chr9", 137953060, "FP", "Phase4 FP A"),
    ("B_FPB1", "chr7", 52087777, "FP", "Phase4 FP B"),
    ("B_FPB2", "chr9", 75383880, "FP", "Phase4 FP B"),
    ("C_V5max1", "chr19", 4639528, "V5_reassign", "V5 reassign hotspot"),
    ("C_V5max2", "chr19", 2235521, "V5_reassign", "V5 reassign hotspot"),
    ("C_V5max3", "chr19", 7405500, "V5_reassign", "V5 reassign hotspot"),
    ("D_SP1", "chr19", 17565944, "SP_extreme", "Self-phasing extreme"),
    ("D_SP2", "chr19", 12452332, "SP_extreme", "Self-phasing extreme"),
    ("D_SP3", "chr19", 12467180, "SP_extreme", "Self-phasing extreme"),
]

WINDOW = 50  # half-window for read fetch around the variant position

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def fetch_hp_map(path: str, chrom: str, pos: int, window: int = WINDOW) -> dict[str, object]:
    """Return {read_name: HP_tag_value_or_None} for primary reads spanning pos.

    HP tag is returned untouched: integer (1, 2, 11, 21, 33) for BL/V3F/V5
    BAMs, or string ("1", "2", "1-1", "2-1", ...) for the paired BAM.
    """
    out: dict[str, object] = {}
    bam = pysam.AlignmentFile(path, "rb")
    try:
        for r in bam.fetch(chrom, max(0, pos - window), pos + window):
            if r.is_unmapped or r.is_secondary or r.is_supplementary:
                continue
            if r.reference_start > pos or r.reference_end < pos:
                continue
            try:
                hp = r.get_tag("HP")
            except KeyError:
                hp = None
            # Keep last occurrence (multi-segment reads share name; HP should agree).
            out[r.query_name] = hp
    finally:
        bam.close()
    return out


def paired_canonical(hp_z: object) -> str | None:
    """Map paired HP:Z string to canonical {"1", "2"}.

    Strings like "1", "1-1", "1-2" → "1"; "2", "2-1", "2-2" → "2".
    Empty / missing → None.
    """
    if hp_z is None:
        return None
    s = str(hp_z).strip()
    if not s:
        return None
    head = s.split("-", 1)[0]
    if head in ("1", "2"):
        return head
    return None


def germline_concordance(v3f_map: dict, paired_map: dict, swap: bool) -> tuple[int, int]:
    """Count germline reads (V3F HP∈{1,2}) where paired canonical agrees.

    With `swap=True` the paired side is flipped (1<->2) before comparison.
    Returns (matches, total_germline_with_paired).
    """
    flip = {"1": "2", "2": "1"}
    matches = 0
    total = 0
    for rn, hp in v3f_map.items():
        if hp not in (1, 2):
            continue
        p = paired_canonical(paired_map.get(rn))
        if p is None:
            continue
        total += 1
        if swap:
            p_use = flip[p]
        else:
            p_use = p
        if (hp == 1 and p_use == "1") or (hp == 2 and p_use == "2"):
            matches += 1
    return matches, total


def pick_orientation(v3f_map: dict, paired_map: dict) -> tuple[bool, float, int]:
    """Return (swap_paired, germline_acc, germline_n).

    Picks whichever orientation maximises germline concordance, tracked per
    site. If too few germline reads to decide (<3) the no-swap orientation is
    used by default and germline_acc is reported as-is.
    """
    m_no, t_no = germline_concordance(v3f_map, paired_map, swap=False)
    m_sw, t_sw = germline_concordance(v3f_map, paired_map, swap=True)
    if t_no == 0 and t_sw == 0:
        return False, float("nan"), 0
    acc_no = m_no / t_no if t_no else 0.0
    acc_sw = m_sw / t_sw if t_sw else 0.0
    if acc_sw > acc_no:
        return True, acc_sw, t_sw
    return False, acc_no, t_no


def read_concordance(track_map: dict, paired_map: dict, swap: bool) -> tuple[int, int]:
    """Count concordant reads where track HP∈{1,2,11,21} maps to paired canonical.

    HP11 collapses to "1" direction, HP21 to "2". HP33 reads are excluded
    (no committed direction). Reads without paired HP also excluded.
    """
    flip = {"1": "2", "2": "1"}
    matches = 0
    total = 0
    for rn, hp in track_map.items():
        if hp == 1 or hp == 11:
            track_dir = "1"
        elif hp == 2 or hp == 21:
            track_dir = "2"
        else:
            continue
        p = paired_canonical(paired_map.get(rn))
        if p is None:
            continue
        total += 1
        if swap:
            p = flip[p]
        if track_dir == p:
            matches += 1
    return matches, total


def fmt_pct(num: int, denom: int) -> str:
    if denom == 0:
        return "n/a"
    return f"{100.0 * num / denom:.1f}%"


# ---------------------------------------------------------------------------
# Per-site analysis
# ---------------------------------------------------------------------------
sanity_rows = []
paired_rows = []
transitions_global = Counter()       # (v3f_tag, v5_tag) -> count, aggregated
new_dir_from_germline = 0            # Layer 1.5 expectation 2 violations
new_dir_from_untagged = 0            # informational
delta_consistency_violations = 0     # Conservation Law A violations
germline_change_violations = 0       # Conservation Law B violations
layer15_pred1_violations = 0         # Layer 1.5 expectation 1 violations

for sid, chrom, pos, klass, _desc in SITES:
    bl = fetch_hp_map(BL_BAM, chrom, pos)
    v3 = fetch_hp_map(V3F_BAM, chrom, pos)
    v5 = fetch_hp_map(V5_BAM, chrom, pos)
    pa = fetch_hp_map(PAIRED_BAM, chrom, pos)

    common = set(v3) & set(v5)

    # --- Conservation Law A: ΔHP33 = -(ΔHP11 + ΔHP21) -----------------------
    def hp_count(m: dict, tag: int) -> int:
        return sum(1 for h in m.values() if h == tag)

    n_v3_33 = hp_count(v3, 33)
    n_v5_33 = hp_count(v5, 33)
    n_v3_11 = hp_count(v3, 11)
    n_v5_11 = hp_count(v5, 11)
    n_v3_21 = hp_count(v3, 21)
    n_v5_21 = hp_count(v5, 21)
    d_33 = n_v5_33 - n_v3_33
    d_11 = n_v5_11 - n_v3_11
    d_21 = n_v5_21 - n_v3_21
    law_a_pass = (d_33 == -(d_11 + d_21))
    if not law_a_pass:
        delta_consistency_violations += 1

    # --- Conservation Law B: HP1/HP2 unchanged ------------------------------
    n_v3_1 = hp_count(v3, 1)
    n_v5_1 = hp_count(v5, 1)
    n_v3_2 = hp_count(v3, 2)
    n_v5_2 = hp_count(v5, 2)
    law_b_pass = (n_v3_1 == n_v5_1) and (n_v3_2 == n_v5_2)
    if not law_b_pass:
        germline_change_violations += 1

    # --- Layer 1.5 read-level transitions -----------------------------------
    transitions = Counter()
    for rn in common:
        a = v3[rn]
        b = v5[rn]
        # Normalise None to 0 for tally readability.
        a_k = a if a is not None else 0
        b_k = b if b is not None else 0
        transitions[(a_k, b_k)] += 1
        transitions_global[(a_k, b_k)] += 1

    n_33to11 = transitions[(33, 11)]
    n_33to21 = transitions[(33, 21)]
    n_germ_to_33 = transitions[(1, 33)] + transitions[(2, 33)]
    n_unt_to_dir = transitions[(0, 11)] + transitions[(0, 21)]
    n_germ_changed = sum(c for (a, b), c in transitions.items() if a in (1, 2) and a != b)

    # Expectation 1: ΔHP11 == n_33to11 (and same for HP21). Allow a small
    # tolerance for reads added/removed to the common set (length differences
    # were 0 across all 15 sites in our probe but coded defensively).
    exp1_a = (d_11 == n_33to11)
    exp1_b = (d_21 == n_33to21)
    layer15_pred1_pass = exp1_a and exp1_b
    if not layer15_pred1_pass:
        layer15_pred1_violations += 1

    # Expectation 2: zero germline → HP33.
    layer15_pred2_pass = (n_germ_to_33 == 0)
    if not layer15_pred2_pass:
        new_dir_from_germline += n_germ_to_33

    new_dir_from_untagged += n_unt_to_dir

    sanity_rows.append({
        "site_id": sid,
        "chrom": chrom,
        "pos": pos,
        "class": klass,
        "n_reads_v3f": len(v3),
        "n_reads_v5": len(v5),
        "v3_hp1": n_v3_1, "v5_hp1": n_v5_1,
        "v3_hp2": n_v3_2, "v5_hp2": n_v5_2,
        "v3_hp11": n_v3_11, "v5_hp11": n_v5_11,
        "v3_hp21": n_v3_21, "v5_hp21": n_v5_21,
        "v3_hp33": n_v3_33, "v5_hp33": n_v5_33,
        "delta_hp11": d_11,
        "delta_hp21": d_21,
        "delta_hp33": d_33,
        "n_33to11": n_33to11,
        "n_33to21": n_33to21,
        "n_germline_to_33": n_germ_to_33,
        "n_germline_changed_any": n_germ_changed,
        "n_untagged_to_directional": n_unt_to_dir,
        "law_A_delta_consistency": "PASS" if law_a_pass else "FAIL",
        "law_B_germline_unchanged": "PASS" if law_b_pass else "FAIL",
        "layer15_pred1_directional_source": "PASS" if layer15_pred1_pass else "FAIL",
        "layer15_pred2_no_germline_demote": "PASS" if layer15_pred2_pass else "FAIL",
    })

    # ----- Paired ground-truth ---------------------------------------------
    swap, germ_acc, germ_n = pick_orientation(v3, pa)
    # PS-class label per spec: clean ≥ 0.70, problem < 0.70 (matches PI report 4).
    ps_class = "clean" if germ_n >= 5 and germ_acc >= 0.70 else "problem"
    if germ_n < 3:
        ps_class = "low_germ_n"

    # Per-read concordance for V5 and BL on common subset (BL ∩ V5 ∩ Paired).
    common_bvp = set(bl) & set(v5) & set(pa)
    sub_bl = {rn: bl[rn] for rn in common_bvp}
    sub_v5 = {rn: v5[rn] for rn in common_bvp}
    sub_pa = {rn: pa[rn] for rn in common_bvp}

    m_v5, t_v5 = read_concordance(sub_v5, sub_pa, swap=swap)
    m_bl, t_bl = read_concordance(sub_bl, sub_pa, swap=swap)

    paired_rows.append({
        "site_id": sid,
        "chrom": chrom,
        "pos": pos,
        "class": klass,
        "n_common_reads": len(common_bvp),
        "germline_n": germ_n,
        "germline_acc": round(germ_acc, 4) if not np.isnan(germ_acc) else float("nan"),
        "ps_class": ps_class,
        "swap_paired_orientation": swap,
        "v5_match": m_v5, "v5_total": t_v5,
        "v5_concordance": round(m_v5 / t_v5, 4) if t_v5 else float("nan"),
        "bl_match": m_bl, "bl_total": t_bl,
        "bl_concordance": round(m_bl / t_bl, 4) if t_bl else float("nan"),
        "v5_minus_bl": (
            round(m_v5 / t_v5 - m_bl / t_bl, 4) if (t_v5 and t_bl) else float("nan")
        ),
    })


# ---------------------------------------------------------------------------
# Aggregates
# ---------------------------------------------------------------------------
total_sites = len(SITES)
sanity_summary = {
    "law_A_violations": delta_consistency_violations,
    "law_B_violations": germline_change_violations,
    "layer15_pred1_violations": layer15_pred1_violations,
    "layer15_pred2_violations_total_reads": new_dir_from_germline,
    "untagged_to_directional_total_reads": new_dir_from_untagged,
}

agg_v5_match = sum(r["v5_match"] for r in paired_rows)
agg_v5_total = sum(r["v5_total"] for r in paired_rows)
agg_bl_match = sum(r["bl_match"] for r in paired_rows)
agg_bl_total = sum(r["bl_total"] for r in paired_rows)
agg_v5_pct = agg_v5_match / agg_v5_total if agg_v5_total else float("nan")
agg_bl_pct = agg_bl_match / agg_bl_total if agg_bl_total else float("nan")

# Clean / problem split
clean_rows = [r for r in paired_rows if r["ps_class"] == "clean"]
problem_rows = [r for r in paired_rows if r["ps_class"] == "problem"]

def pooled(rows, key_match, key_total):
    m = sum(r[key_match] for r in rows)
    t = sum(r[key_total] for r in rows)
    return (m / t if t else float("nan"), m, t)

clean_v5 = pooled(clean_rows, "v5_match", "v5_total")
clean_bl = pooled(clean_rows, "bl_match", "bl_total")
prob_v5 = pooled(problem_rows, "v5_match", "v5_total")
prob_bl = pooled(problem_rows, "bl_match", "bl_total")

# Site-level wins (clean PS only, fairer)
v5_wins_clean = sum(1 for r in clean_rows if r["v5_concordance"] > r["bl_concordance"])
bl_wins_clean = sum(1 for r in clean_rows if r["bl_concordance"] > r["v5_concordance"])
ties_clean = len(clean_rows) - v5_wins_clean - bl_wins_clean
v5_wins_prob = sum(1 for r in problem_rows if r["v5_concordance"] > r["bl_concordance"])
bl_wins_prob = sum(1 for r in problem_rows if r["bl_concordance"] > r["v5_concordance"])
ties_prob = len(problem_rows) - v5_wins_prob - bl_wins_prob

# ---------------------------------------------------------------------------
# Verdict
# ---------------------------------------------------------------------------
def determine_verdict() -> str:
    if (delta_consistency_violations == 0 and germline_change_violations == 0
            and layer15_pred1_violations == 0 and new_dir_from_germline == 0):
        return "PASS"
    # Soft warn if only the (informational) untagged→directional bucket is non-zero.
    if (delta_consistency_violations == 0 and germline_change_violations == 0
            and layer15_pred1_violations == 0):
        return "WARN"
    return "FAIL"


VERDICT = determine_verdict()

# ---------------------------------------------------------------------------
# Write TSVs
# ---------------------------------------------------------------------------
def write_tsv(path: Path, rows: list[dict]) -> int:
    if not rows:
        path.write_text("")
        return 0
    headers = list(rows[0].keys())
    with path.open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=headers, delimiter="\t")
        w.writeheader()
        for r in rows:
            w.writerow(r)
    return len(rows) + 1  # data rows + header


sanity_tsv_lines = write_tsv(DATA_DIR / "sanity_check.tsv", sanity_rows)
paired_tsv_lines = write_tsv(DATA_DIR / "paired_ground_truth.tsv", paired_rows)

# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------
def savefig(fig, path: Path):
    fig.tight_layout()
    fig.savefig(path, dpi=170, bbox_inches="tight")
    plt.close(fig)


# Fig 06a — Conservation Law A & B per-site bar chart -----------------------
fig, ax = plt.subplots(figsize=(13.5, 5.6))
labels = [r["site_id"] for r in sanity_rows]
x = np.arange(len(labels))
width = 0.27
delta_hp33 = [r["delta_hp33"] for r in sanity_rows]
neg_d11_d21 = [-(r["delta_hp11"] + r["delta_hp21"]) for r in sanity_rows]
germline_drift = [
    (r["v5_hp1"] - r["v3_hp1"]) + (r["v5_hp2"] - r["v3_hp2"]) for r in sanity_rows
]
ax.bar(x - width, delta_hp33, width, label="ΔHP33 (V5 - V3F)", color="#E65100")
ax.bar(x, neg_d11_d21, width, label="-(ΔHP11 + ΔHP21)", color="#1565C0")
ax.bar(x + width, germline_drift, width,
       label="ΔHP1+ΔHP2 (germline drift; expected 0)", color="#2E7D32")
ax.axhline(0, color="black", lw=0.6)
ax.set_xticks(x)
ax.set_xticklabels(labels, rotation=35, ha="right", fontsize=9)
ax.set_ylabel("Read-count delta")
ax.set_title(
    "Fig 06a — Conservation Law A (ΔHP33 = -(ΔHP11+ΔHP21)) & Law B (Δgermline = 0)\n"
    f"Per site (15 sites). Law A violations: {delta_consistency_violations}/{total_sites}; "
    f"Law B violations: {germline_change_violations}/{total_sites}"
)
ax.legend(loc="upper left", fontsize=9)
ax.grid(axis="y", alpha=0.25)
savefig(fig, FIG_SANITY_DIR / "fig06a_conservation_verification.png")

# Fig 06b — Layer 1.5 transitions (V3F -> V5) -------------------------------
fig, axes = plt.subplots(1, 2, figsize=(14, 5.6),
                        gridspec_kw={"width_ratios": [1.6, 1.0]})
ax1 = axes[0]
keep_keys = [
    ((33, 11), "33→11", "#1565C0"),
    ((33, 21), "33→21", "#42A5F5"),
    ((33, 33), "33→33 (held)", "#E65100"),
    ((11, 11), "11→11", "#90CAF9"),
    ((21, 21), "21→21", "#BBDEFB"),
    ((1, 1), "1→1", "#2E7D32"),
    ((2, 2), "2→2", "#66BB6A"),
    ((1, 33), "1→33 (BUG)", "#B71C1C"),
    ((2, 33), "2→33 (BUG)", "#D32F2F"),
    ((0, 11), "0→11 (untagged→dir)", "#9E9E9E"),
    ((0, 21), "0→21 (untagged→dir)", "#BDBDBD"),
]
counts = [transitions_global[k] for k, _, _ in keep_keys]
labels_t = [lbl for _, lbl, _ in keep_keys]
colors = [c for _, _, c in keep_keys]
y = np.arange(len(labels_t))[::-1]
ax1.barh(y, counts, color=colors, edgecolor="black", linewidth=0.4)
for yy, n in zip(y, counts):
    ax1.text(n + max(counts) * 0.01, yy, str(n), va="center", fontsize=9)
ax1.set_yticks(y)
ax1.set_yticklabels(labels_t, fontsize=9)
ax1.set_xlabel("Reads (sum across 15 sites)")
ax1.set_title("V3F → V5 read-tag transitions (Layer 1.5 footprint)")
ax1.grid(axis="x", alpha=0.25)

ax2 = axes[1]
exp1_pass_cnt = sum(
    1 for r in sanity_rows if r["layer15_pred1_directional_source"] == "PASS"
)
exp2_pass_cnt = sum(
    1 for r in sanity_rows if r["layer15_pred2_no_germline_demote"] == "PASS"
)
bars = ax2.bar(
    ["Pred 1\n(33→dir = ΔHP)", "Pred 2\n(no germline→33)"],
    [exp1_pass_cnt, exp2_pass_cnt],
    color=["#1565C0", "#2E7D32"],
)
for b, v in zip(bars, [exp1_pass_cnt, exp2_pass_cnt]):
    ax2.text(b.get_x() + b.get_width() / 2, v + 0.1, f"{v}/{total_sites}",
             ha="center", va="bottom", fontsize=11, fontweight="bold")
ax2.set_ylim(0, total_sites + 1)
ax2.set_ylabel("Sites passing")
ax2.set_title("Layer 1.5 expectation pass rate")
ax2.grid(axis="y", alpha=0.25)

fig.suptitle("Fig 06b — Layer 1.5 expectations across 15 sites", fontsize=12, y=1.02)
savefig(fig, FIG_SANITY_DIR / "fig06b_layer15_expectation.png")

# Fig 07a — V5 vs BL paired concordance per site ----------------------------
fig, ax = plt.subplots(figsize=(13.5, 5.6))
x = np.arange(len(paired_rows))
v5c = [r["v5_concordance"] if not np.isnan(r["v5_concordance"]) else 0 for r in paired_rows]
blc = [r["bl_concordance"] if not np.isnan(r["bl_concordance"]) else 0 for r in paired_rows]
ax.bar(x - 0.2, v5c, 0.4, label="V5 vs Paired", color="#1565C0")
ax.bar(x + 0.2, blc, 0.4, label="Baseline vs Paired", color="#9E9E9E")
ax.set_xticks(x)
ax.set_xticklabels([r["site_id"] for r in paired_rows], rotation=35, ha="right", fontsize=9)
ax.set_ylim(0, 1.05)
ax.set_ylabel("Per-read concordance with paired tumor BAM")
ax.axhline(0.5, color="grey", lw=0.6, ls="--", label="random=0.5")
# Annotate PS class.
for xi, r in zip(x, paired_rows):
    ax.text(xi, 1.01, r["ps_class"][:1].upper(), ha="center", va="bottom",
            fontsize=8, color="#444")
ax.set_title(
    "Fig 07a — V5 vs Baseline per-read paired concordance, 15 sites\n"
    f"Aggregate (orientation-corrected): V5={agg_v5_pct:.1%} ({agg_v5_match}/{agg_v5_total}); "
    f"BL={agg_bl_pct:.1%} ({agg_bl_match}/{agg_bl_total})"
)
ax.legend(loc="lower right", fontsize=9)
ax.grid(axis="y", alpha=0.25)
savefig(fig, FIG_PAIRED_DIR / "fig07a_paired_concordance_per_site.png")

# Fig 07b — clean PS vs problem PS comparison --------------------------------
fig, ax = plt.subplots(figsize=(9.5, 5.6))
groups = ["clean PS", "problem PS"]
v5_vals = [clean_v5[0] if not np.isnan(clean_v5[0]) else 0,
           prob_v5[0] if not np.isnan(prob_v5[0]) else 0]
bl_vals = [clean_bl[0] if not np.isnan(clean_bl[0]) else 0,
           prob_bl[0] if not np.isnan(prob_bl[0]) else 0]
xb = np.arange(2)
ax.bar(xb - 0.18, v5_vals, 0.36, label="V5", color="#1565C0")
ax.bar(xb + 0.18, bl_vals, 0.36, label="Baseline", color="#9E9E9E")
for xi, v, lbl_n in zip(xb - 0.18, v5_vals, [clean_v5[2], prob_v5[2]]):
    ax.text(xi, v + 0.02, f"{v:.1%}\n(n={lbl_n})", ha="center", va="bottom", fontsize=9)
for xi, v, lbl_n in zip(xb + 0.18, bl_vals, [clean_bl[2], prob_bl[2]]):
    ax.text(xi, v + 0.02, f"{v:.1%}\n(n={lbl_n})", ha="center", va="bottom", fontsize=9)
ax.set_xticks(xb)
ax.set_xticklabels([
    f"{g}\nsites: {n}" for g, n in zip(groups, [len(clean_rows), len(problem_rows)])
])
ax.set_ylim(0, 1.15)
ax.axhline(0.5, color="grey", lw=0.6, ls="--", label="random=0.5")
ax.set_ylabel("Pooled per-read concordance with Paired")
ax.set_title(
    "Fig 07b — Clean PS vs problem PS (orientation-corrected)\n"
    f"Site wins (clean): V5={v5_wins_clean}, BL={bl_wins_clean}, tie={ties_clean}; "
    f"(problem): V5={v5_wins_prob}, BL={bl_wins_prob}, tie={ties_prob}"
)
ax.legend(fontsize=9)
ax.grid(axis="y", alpha=0.25)
savefig(fig, FIG_PAIRED_DIR / "fig07b_clean_vs_problem_ps.png")

# ---------------------------------------------------------------------------
# Stdout summary (so the orchestrator can log it)
# ---------------------------------------------------------------------------
print("=== V5 Sanity & Paired Concordance ===")
print(f"Sites analysed: {total_sites}")
print(
    "Conservation: Law A violations="
    f"{delta_consistency_violations}/{total_sites}; "
    f"Law B violations={germline_change_violations}/{total_sites}"
)
print(
    "Layer 1.5: pred1 violations="
    f"{layer15_pred1_violations}/{total_sites}; "
    f"pred2 reads (germline→33)={new_dir_from_germline}; "
    f"untagged→directional reads={new_dir_from_untagged}"
)
print(
    f"Aggregate paired concordance: V5={agg_v5_pct:.4f} ({agg_v5_match}/{agg_v5_total}); "
    f"BL={agg_bl_pct:.4f} ({agg_bl_match}/{agg_bl_total})"
)
print(f"Clean PS sites={len(clean_rows)} / problem PS sites={len(problem_rows)}")
print(
    "Clean PS V5={:.1%} BL={:.1%} | Problem PS V5={:.1%} BL={:.1%}".format(
        clean_v5[0] if not np.isnan(clean_v5[0]) else float("nan"),
        clean_bl[0] if not np.isnan(clean_bl[0]) else float("nan"),
        prob_v5[0] if not np.isnan(prob_v5[0]) else float("nan"),
        prob_bl[0] if not np.isnan(prob_bl[0]) else float("nan"),
    )
)
print(f"VERDICT: {VERDICT}")
print(f"sanity_check.tsv lines = {sanity_tsv_lines}")
print(f"paired_ground_truth.tsv lines = {paired_tsv_lines}")
for fp in (
    FIG_SANITY_DIR / "fig06a_conservation_verification.png",
    FIG_SANITY_DIR / "fig06b_layer15_expectation.png",
    FIG_PAIRED_DIR / "fig07a_paired_concordance_per_site.png",
    FIG_PAIRED_DIR / "fig07b_clean_vs_problem_ps.png",
):
    sz = os.path.getsize(fp) if fp.exists() else 0
    print(f"FIG {fp.name}: {sz/1024:.1f} KB")
